### ISSUE TITLE
Multiple url

### ISSUE THREAD

**Issue by Ashish117** [julietcetera/web-scraper-js#1]
How can I scrape multiple pages.

**Comment by julietcetera** [comment]
By doing multiple calls to the same function.

**Comment by Ashish117** [comment]
I am using the function in module.exports and i need to return the data so
calling the function for multiple url is a bad practice right?

**Comment by julietcetera** [comment]
I don't see why calling a function multiple times is bad practice since that's one of the main reasons functions exist.

**Comment by Ashish117** [comment]
```js
module.exports = {
  pdata: async (req, res) => {
    let result1 = await webscraper.scrape({
        url: 'example1.com,
        tags: {
            text: {
                "ProductName":  ".product-name",
                "Product Price": ".product-price"
            }
        }
    });
    let result2 = await webscraper.scrape({
      url: 'example2.com',
      tags: {
          text: {
              "ProductName": ".product-name",
              "Product Price": ".product-price",
          }
      }
  });
  let model = [ result1.ProductName, result2.ProductName ];
  var result = {
    title:  model
  };
  //res.json(result);
  console.log(result)
  return result;
  }
};
```

This is how I tried but i need to add more sites and export the results asyncly

**Comment by julietcetera** [comment]
It is bad practice to violate the DRY principle... You should just use arrays. It would look something like this:
```js
let results = Promise.all([/* list of urls */].map(async url => {
    return await webscraper.scrape({
        url: url,
        tags: /*...*/
    });
}));
```

**Comment by Ashish117** [comment]
Wow, Thanks. 
Also 
`text: {
              "ProductName": ".product-name",
              "Product Price": ".product-price",
          }`

I don't want product price to be in a separate array so i tried this:
`text: {
              "ProductName": ".product-name", ".product-price"
          }`

But did't work, is there a way to solve this

**Comment by julietcetera** [comment]
That's not even valid JSON syntax. And I see no reason to add such features to the scraper as you could simply modify the returned value per URL.
```js
let results = Promise.all([/* list of urls */].map(async url => {
    let result = await webscraper.scrape({
        url: url,
        tags: /*...*/
    });
    return [ result["ProductName"], result["Product Price"] ];
}));
```

**Comment by Ashish117** [comment]
I tried this and it will emit
 `null, null`

**Comment by julietcetera** [comment]
Debug it then?

**Comment by Ashish117** [comment]
Tried, can you help?

**Comment by Ashish117** [comment]
@julietcetera I am trying with a lot of url request so now it returns status 500, How to pass user-Agents

**Comment by Ashish117** [comment]
@julietcetera I am trying to get data from more than 50 pages and website returns Status Code 500, it will work if i try with 20 url, Is there a way to bypass this like adding a wait time for next queue url or something? im not good at this.
